### PR TITLE
WIP: Swapable urban demand data, with system to handle configuration

### PR DESCRIPTION
**Pull request by jrising**
This adds an UrbanDemand notebook and a system for reading demand data either from USGS or from a configurable file.

Maura, can you extend the UrbanDemand notebook with a description of the numbers and a map comparison (using the `usmap` function)?  And can you also write a unit test of the data loading stuff, basically checking that it's pulling the right data into the right locations in the water demand vector and leaving the other data alone?

### CODE REVIEW

**Comment by jrising** [comment]
Merging this in, since I accidentally added a commit on agriculture documentation here too.

**Comment by LaurelineJ** [comment]
I am under the impression that there now only Maura's number in, and that there is not a configuration function to set the urban demand numbers back to the USGS ones.
Also, does model.jl need to include PopulationDemand.jl systematically ?

**Comment by jrising** [comment]
That's not the intention.  It should be that USGS numbers are the default--
whichever ones are in demand/simulation2010demanddata.csv.  Only having the
right values in the config file will give you Maura's numbers.

The PopulationDemand component needs to be loaded if Maura's numbers are
configured our you'll get an error.

- James

**Comment by LaurelineJ** [comment]
Both Maria and I run into errors when we run simulate with the latest
version on the master.

**Comment by jrising** [comment]
Can you try again?  I just made three changes:
 - Removed the urban == USGS check.  This seems redundant.
 - Added PopulationDemand to the model script.
 - Checked for NAs in Maura's values, and dropped these rows.

**Comment by LaurelineJ** [comment]
All is good now. There are still issues with balance and return balance not
equal to 0 when performing optimization. I am working on this for the new
version of the allocation problem on the "costmodel" branch (which is now
running but has not been validated).

**Pull request merged**
